time: 60
item: 'GOLDEN_APPLE'
animation: true
detectionRange: 50
mobDamage: true
tombstone: true
totem: false
permission: 'revive.admin'
messages:
  armorstand:
    stand0: '&6Right click'
    stand1: '&6to revive!'
  title:
    title: '&cYou got knocked out!'
    subtitle: '&4Get revived by someone or you bleed out.'
  actionbar: '&cYou will bleed out in'
  wrongUsage: '&cWrong usage of the command /revive settings'
  selectNewReviveItem: '&6[Revive] &bClick on an item in your inventory to select the new reviving item.'
  pressSneak: '&aNo player nearby. Press &6Sneak &ato die instantly'
  cantPressSneak: '&4There is a player nearby!'
  playerDiedMessage: '&cThe player &6[player] &cbled out.'
  playerKnocked: '&7The player &6[player] &7has been knocked out.'
